# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# The most common configuration options are documented and commented below.
# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

# Every Vagrant development environment requires a box. You can search for
# boxes at https://vagrantcloud.com/search.

Vagrant.configure("2") do |config|
  config.vm.box = "offensive-security/kali-linux"
  config.vm.box_check_update = true
  config.vm.hostname = "Silence"
  config.vm.provider :virtualbox do |v|
    v.name = "Silence"
    v.memory = "4096"
    v.cpus = 2
    v.gui = true
  end
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
    bridge: "en0: Wi-Fi (AirPort)"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "kali-config.yml"
  end

  # config.vm.provision :shell, :path => "bootstrap.sh"
end
